"""
Data models for search documents and results.
Defines Pydantic models for MongoDB document structure.
"""

from datetime import datetime, timezone
from typing import List, Optional, Any
from pydantic import BaseModel, Field
from app.models.enums import SearchStatus, SearchProvider


class SearchResult(BaseModel):
    """
    Individual search result from external search provider.
    
    Attributes:
        rank: Organic search ranking position (1-10).
        title: Parsed title text of the search item.
        url: Destination URL web link.
        snippet: Snippet description text, if available.
    """
    rank: int = Field(..., description="The organic search ranking position (1-10)")
    title: str = Field(..., description="The parsed title text of the search item")
    url: str = Field(..., description="The destination URL web link")
    snippet: Optional[str] = Field(None, description="The snippet description or None if missing")


class SearchDocument(BaseModel):
    """
    Complete search document stored in MongoDB.
    
    Attributes:
        keyword: Normalized lowercase search keyphrase.
        version: Chronological history version tracking ID.
        provider: Search provider identifier (default: SERPER).
        status: Success or NO_RESULTS enum classification.
        ai_synthesis: One-paragraph synthesis generated by Mistral 7B.
        results: List of search results.
        searched_at: ISO 8601 timestamp of search execution.
        performance_history: Historical log of lookup timestamps and processing metrics.
    """
    keyword: str = Field(..., description="The normalized lowercase search keyphrase")
    version: int = Field(..., description="Chronological history version tracking ID")
    provider: SearchProvider = Field(default=SearchProvider.SERPER)
    status: SearchStatus = Field(..., description="Success or No Results enum classification")
    ai_synthesis: Optional[str] = Field(None, description="One-paragraph synthesis generated by Mistral 7B")
    results: List[SearchResult] = Field(default=[], description="Nested list array of search results")
    searched_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 string timestamp representation of the search execution"
    )
    performance_history: List[Any] = Field(
        default=[], 
        description="Historical log array of lookup timestamps and processing turnaround metrics"
    )
