"""
Response schema models for API output serialization.
Defines Pydantic models for outgoing response payloads.
"""

from typing import List, Optional, Any
from pydantic import BaseModel, Field


class SearchResultResponse(BaseModel):
    """
    Individual search result in API response.
    
    Attributes:
        rank: Organic search ranking position (1-10).
        title: Parsed title text of the search result item.
        url: Destination URL web link.
        snippet: Descriptive snippet text or None if missing.
    """
    rank: int = Field(..., description="The organic search ranking position (1-10)")
    title: str = Field(..., description="The parsed title text of the search result item")
    url: str = Field(..., description="The destination URL web link")
    snippet: Optional[str] = Field(None, description="The descriptive snippet text string or None if missing")


class SearchResponse(BaseModel):
    """
    Complete search response payload.
    
    Attributes:
        keyword: Normalized lowercase search keyphrase.
        version: Incremental chronological history version ID.
        cached: Flag indicating if data was retrieved from cache.
        searched_at: ISO 8601 timestamp of search execution.
        ai_synthesis: One-paragraph synthesis generated by Mistral 7B.
        results: Collection of organic matching search results.
        performance_history: Historical log of query timestamps and execution speeds.
    """
    keyword: str = Field(..., description="The normalized lowercase search keyphrase")
    version: int = Field(..., description="The incremental chronological history tracking version ID")
    cached: bool = Field(..., description="Flag indicating whether data was retrieved from cache")
    searched_at: str = Field(..., description="ISO 8601 string timestamp representation of the search execution")
    ai_synthesis: Optional[str] = Field(None, description="One-paragraph abstract synthesis generated by Mistral 7B")
    results: List[SearchResultResponse] = Field(default=[], description="Collection array of organic matching elements")
    performance_history: List[Any] = Field(
        default=[], 
        description="Historical compilation array mapping query entry timestamps to computing execution speeds"
    )
